name: Cypress Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy-run-smoke
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          VALID_USER_LOGIN: ${{ secrets.VALID_USER_LOGIN }}
          VALID_USER_PASSWORD: ${{ secrets.VALID_USER_PASSWORD }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: videos
          path: ./cypress/videos/
          retention-days: 1
